In [408]:
import seaborn as sns
import pandas as pd
import numpy as np
from pathlib import Path
from matplotlib import pyplot as plt
from matplotlib.ticker import MaxNLocator
import math
from pathlib import Path

from xarch_tokenizers.logging.report_utils import (
    load_predictions,
    load_all_samples,
    clean_model_name,
)
from xarch_tokenizers.logging.plot_utils import (
    setup_styles,
    get_new_6_fig,
    MODEL_TO_COLOR,
    get_new_fig,
)


setup_styles()
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [409]:
## same as exploratory plotting notebook `paper-benchmark-plots.ipynb`
def get_canonical_and_perturbed_df(
    samples,
    only_keep_canonical_true: bool = False,
    keep_remains_or_becomes_correct: bool = False,
    only_keep_perturbed_true: bool = False,
    verbose: bool = False,
):
    """returns filtered out samples too"""
    if (
        (only_keep_canonical_true and keep_remains_or_becomes_correct)
        or (only_keep_canonical_true and only_keep_perturbed_true)
        or (keep_remains_or_becomes_correct and only_keep_perturbed_true)
    ):
        raise ValueError(
            f"Please pass these exclusively, only_keep_canonical_true: true for canonical, model_name true, keep_remains_or_becomes_correct: True to include the ones where the perturbed version becomes correct"
        )
    if verbose:
        print(f"Processing {len(samples)} examples")
    canonical_samples = samples[samples["is_canonical"]]
    perturbed_samples = samples[~samples["is_canonical"]]
    canonical_values = canonical_samples[["set_id", "model_name", METRIC]].rename(
        columns={METRIC: f"canonical_{METRIC}"}
    )

    perturbed_samples = perturbed_samples.merge(
        canonical_values, on=["set_id", "model_name"], how="left"
    )
    perturbed_samples[f"canonical-perturbed_{METRIC}"] = (
        perturbed_samples[f"canonical_{METRIC}"] - perturbed_samples[METRIC]
    )

    if only_keep_canonical_true:
        correct_canonical_pairs = canonical_samples[canonical_samples[METRIC] == 1][
            ["set_id", "model_name"]
        ]
        if verbose:
            print(
                f"Cleaning samples, will be dropping entries (set_id-model pairs) where the canonical is predicted wrong."
            )
            print(
                f"Keeping {len(correct_canonical_pairs)} correct pairs, dropping {len(canonical_samples) - len(correct_canonical_pairs)} entries."
            )

        canonical_samples = canonical_samples[canonical_samples[METRIC] == 1]

        # Step 3: Filter perturbed_samples to keep only rows with correct canonical pairs
        # Method 1: Using merge (RECOMMENDED)
        perturbed_samples = perturbed_samples.merge(
            correct_canonical_pairs,
            on=["set_id", "model_name"],
            how="inner",  # Only keep rows that exist in both
        )
        samples = pd.concat((canonical_samples, perturbed_samples), ignore_index=True)

    if keep_remains_or_becomes_correct:
        # Get pairs where perturbed samples are correct (becomes or remains correct)
        correct_perturbed_pairs = perturbed_samples[perturbed_samples[METRIC] == 1][
            ["set_id", "model_name"]
        ].drop_duplicates()

        # Get pairs where canonical samples are correct (remains correct)
        correct_canonical_pairs = canonical_samples[canonical_samples[METRIC] == 1][
            ["set_id", "model_name"]
        ]

        # Combine: pairs that either remain correct OR become correct
        remains_or_becomes_correct = pd.concat(
            [correct_canonical_pairs, correct_perturbed_pairs]
        ).drop_duplicates()

        # Filter both datasets to only include these pairs
        canonical_samples = canonical_samples.merge(
            remains_or_becomes_correct, on=["set_id", "model_name"], how="inner"
        )

        perturbed_samples = perturbed_samples.merge(
            remains_or_becomes_correct, on=["set_id", "model_name"], how="inner"
        )
        samples = pd.concat((canonical_samples, perturbed_samples), ignore_index=True)
        if verbose:
            print(f"After filtering:{len(samples)}")
    if only_keep_perturbed_true:
        # Get pairs where perturbed samples are correct (becomes or remains correct)
        correct_perturbed_pairs = perturbed_samples[perturbed_samples[METRIC] == 1][
            ["set_id", "model_name"]
        ].drop_duplicates()

        # Get pairs where canonical samples are correct (remains correct)
        wrong_canonical_pairs = canonical_samples[canonical_samples[METRIC] == 0][
            ["set_id", "model_name"]
        ]
        # Find cases where canonical wrong AND perturbed correct (recovery cases)
        becomes_correct = pd.merge(
            wrong_canonical_pairs,
            correct_perturbed_pairs,
            how="inner",
            on=["set_id", "model_name"],
        )

        # Filter both datasets to only include recovery cases
        canonical_samples = canonical_samples.merge(
            becomes_correct, on=["set_id", "model_name"], how="inner"
        )

        perturbed_samples = perturbed_samples.merge(
            becomes_correct, on=["set_id", "model_name"], how="inner"
        )

        samples = pd.concat([canonical_samples, perturbed_samples], ignore_index=True)
        if verbose:
            print(f"After filtering: {len(samples)}")

    return samples, canonical_samples, perturbed_samples

# Let's Create Summary

In [410]:
OUTPUT_DIR = Path("./output/results-v5")
OUTPUT_DIR_ = OUTPUT_DIR / "summary"
METRIC = "acc_norm"
# read all samples
base_dir = Path("../results/paper-v5").resolve().absolute()

# # keeps set_id, model pairs that are correct for canonical
# suffix = "(Still correct)"
# only_keep_canonical_true = True
# keep_remains_or_becomes_correct = False
# only_keep_perturbed_true = False

# suffix = "(Remains or Becomes Correct)"
# only_keep_canonical_true = False
# keep_remains_or_becomes_correct = True
# only_keep_perturbed_true = False

# suffix = "(Flipped to correct)"
# only_keep_canonical_true = False
# keep_remains_or_becomes_correct = False
# only_keep_perturbed_true = True

# suffix = "(All)"
# only_keep_canonical_true = False
# keep_remains_or_becomes_correct = False
# only_keep_perturbed_true = False

code_pattern = "*"
title_pattern = "All Datasets"
OUTPUT_DIR = OUTPUT_DIR_ / "all"

OUTPUT_DIR = OUTPUT_DIR
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)
base_dir.exists()
pred_files = list([p for p in base_dir.rglob(f"samples{code_pattern}.jsonl")])
len(pred_files), pred_files[:5]

(2528,
 [PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_general_currency_symbol_2025-09-20T10-09-51.814046.jsonl'),
  PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_farsi_canonical_2025-09-20T16-14-33.757080.jsonl'),
  PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_chinese_ocr_errors_2025-09-20T11-23-04.491388.jsonl'),
  PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_italian_typographical_errors_2025-09-20T10-31-24.441216.jsonl'),
  PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_italian_grammatical_errors_2025-09-20T10-31-24.441216.jsonl')])

In [411]:
## Read all samples into a DataFrame
## exclude general dataset for now
all_samples = load_all_samples(
    base_dir,
    patterns=[code_pattern],
    exclude_patterns=["general"],
    flatten_doc=True,
    match_date=False,
    simplify_df=True,
)

2366 [PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_farsi_canonical_2025-09-20T16-14-33.757080.jsonl'), PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_chinese_ocr_errors_2025-09-20T11-23-04.491388.jsonl'), PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_italian_typographical_errors_2025-09-20T10-31-24.441216.jsonl'), PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_italian_grammatical_errors_2025-09-20T10-31-24.441216.jsonl'), PosixPath('/Users/gsaltintas/code/phd/tokenizers/results/paper-v5/r-three__supertoken_models-llama_facebook-xglm-564M/samples_tokenizer_robustness_completion_math_space_removal_2025-09-20T15-57-08.872287.jsonl')]
tokenizer_robustness_completion_farsi_canonical
tokenizer_robustness_completion_chinese_ocr_errors
tokenizer_robustness_completion_italian_typographical_errors
tokenizer_robustness_completion_italian_grammatical_errors
tokenizer_robustness_completion_math_space_removal
tokenizer_robustness_completion_english_contractions
tokenizer_robustness_completion_stem_morpheme_separation
tokenizer_robustness_completion_italian_numerical_formats
tokenizer_robustness_completion_english_emoji_substitution
tokenizer_robustness_completion_chinese_optional_diacritics
tokenizer_robustness_completion_stem_compounds
tokenizer_robustness_completion_english_spaced_styling
tokenizer_robustness_completion_italian_code_language_script_switching
tokenizer_robustness_completion_farsi_arabic_keyboard_for_farsi
tokenizer_robustness_completion_stem_double_struck
tokenizer_robustness_completion_stem_latex
tokenizer_robustness_completion_english_homoglyphs
tokenizer_robustness_completion_italian_date_formats
tokenizer_robustness_completion_english_lowercase
tokenizer_robustness_completion_farsi_romanization
tokenizer_robustness_completion_english_macron_diacritic
tokenizer_robustness_completion_english_scripted_text
tokenizer_robustness_completion_math_italian
tokenizer_robustness_completion_chinese_partially_romanized
tokenizer_robustness_completion_italian_canonical
tokenizer_robustness_completion_stem_canonical
tokenizer_robustness_completion_italian_plausible_diacritics_errors
tokenizer_robustness_completion_english_superscript_subscript_styling
tokenizer_robustness_completion_chinese_keyboard_proximity_errors
tokenizer_robustness_completion_italian_keyboard_proximity_errors
tokenizer_robustness_completion_turkish_equivalent_expressions
tokenizer_robustness_completion_stem_character_deletion
tokenizer_robustness_completion_italian_english_keyboard
tokenizer_robustness_completion_chinese_space_removal
tokenizer_robustness_completion_stem_colloquial
tokenizer_robustness_completion_chinese_code_language_script_switching
tokenizer_robustness_completion_stem_superscript_subscript
tokenizer_robustness_completion_stem_space_removal
tokenizer_robustness_completion_english_character_deletion
tokenizer_robustness_completion_chinese_equivalent_expressions
tokenizer_robustness_completion_chinese_colloquial
tokenizer_robustness_completion_italian_web_search_query
tokenizer_robustness_completion_stem_spelled_out
tokenizer_robustness_completion_stem_strikethrough
tokenizer_robustness_completion_math_spelled_out
tokenizer_robustness_completion_farsi_number_romanization
tokenizer_robustness_completion_italian_web_search_query
tokenizer_robustness_completion_stem_unicode_formatting
tokenizer_robustness_completion_italian_english_keyboard
tokenizer_robustness_completion_english_colloquial
tokenizer_robustness_completion_italian_keyboard_proximity_errors
tokenizer_robustness_completion_stem_fullwidth_characters
tokenizer_robustness_completion_farsi_word_spacing_zero-width_characters_extra_space
tokenizer_robustness_completion_english_space_removal
tokenizer_robustness_completion_english_grammatical_errors
tokenizer_robustness_completion_stem_equivalent_expressions
tokenizer_robustness_completion_english_compounds
tokenizer_robustness_completion_italian_plausible_diacritics_errors
tokenizer_robustness_completion_turkish_spelled_out
tokenizer_robustness_completion_stem_scripted_text
tokenizer_robustness_completion_italian_canonical
tokenizer_robustness_completion_farsi_keyboard_proximity_errors
tokenizer_robustness_completion_turkish_grammatical_errors
tokenizer_robustness_completion_stem_diacriticized_styling
tokenizer_robustness_completion_stem_upside_down_rotated
tokenizer_robustness_completion_english_word_reordering
tokenizer_robustness_completion_stem_typographical_errors
tokenizer_robustness_completion_english_capitalization
tokenizer_robustness_completion_italian_date_formats
tokenizer_robustness_completion_chinese_traditional
tokenizer_robustness_completion_italian_code_language_script_switching
tokenizer_robustness_completion_english_inflections
tokenizer_robustness_completion_chinese_romanization
tokenizer_robustness_completion_chinese_canonical
tokenizer_robustness_completion_farsi_optional_diacritics
tokenizer_robustness_completion_chinese_spelled_out
tokenizer_robustness_completion_italian_numerical_formats
tokenizer_robustness_completion_stem_enclosed_characters
tokenizer_robustness_completion_math_chinese
tokenizer_robustness_completion_english_canonical
tokenizer_robustness_completion_chinese_word_spacing_zero-width_characters_extra_space
tokenizer_robustness_completion_italian_grammatical_errors
tokenizer_robustness_completion_italian_typographical_errors
tokenizer_robustness_completion_stem_unusual_formatting
tokenizer_robustness_completion_italian_orthographic_errors
tokenizer_robustness_completion_italian_phonetic_spelling
tokenizer_robustness_completion_stem_typographical_errors
tokenizer_robustness_completion_turkish_orthographic_errors
tokenizer_robustness_completion_stem_upside_down_rotated
tokenizer_robustness_completion_math_canonical
tokenizer_robustness_completion_chinese_traditional
tokenizer_robustness_completion_chinese_romanization
tokenizer_robustness_completion_chinese_canonical
tokenizer_robustness_completion_italian_abbreviations
tokenizer_robustness_completion_chinese_spelled_out
tokenizer_robustness_completion_english_ocr_errors
tokenizer_robustness_completion_stem_enclosed_characters
tokenizer_robustness_completion_chinese_word_spacing_zero-width_characters_extra_space
tokenizer_robustness_completion_math_turkish
tokenizer_robustness_completion_stem_unusual_formatting
tokenizer_robustness_completion_english_orthographic_errors
tokenizer_robustness_completion_italian_spelled_out
tokenizer_robustness_completion_stem_strikethrough
tokenizer_robustness_completion_stem_unicode_formatting
tokenizer_robustness_completion_turkish_date_formats
tokenizer_robustness_completion_turkish_keyboard_proximity_errors
tokenizer_robustness_completion_stem_spelled_out
tokenizer_robustness_completion_stem_equivalent_expressions
tokenizer_robustness_completion_stem_fullwidth_characters
tokenizer_robustness_completion_math_decorative_unicode
tokenizer_robustness_completion_italian_dialects
tokenizer_robustness_completion_farsi_code_language_script_switching
tokenizer_robustness_completion_italian_similar_words
tokenizer_robustness_completion_farsi_equivalent_expressions
tokenizer_robustness_completion_english_character_substitution
tokenizer_robustness_completion_stem_scripted_text
tokenizer_robustness_completion_turkish_code_language_script_switching
tokenizer_robustness_completion_italian_capitalization
tokenizer_robustness_completion_italian_contractions
tokenizer_robustness_completion_english_hyphenated_spelling
tokenizer_robustness_completion_stem_diacriticized_styling
tokenizer_robustness_completion_math_farsi
tokenizer_robustness_completion_farsi_colloquial
tokenizer_robustness_completion_italian_capitalization
tokenizer_robustness_completion_italian_contractions
tokenizer_robustness_completion_turkish_typographical_errors
tokenizer_robustness_completion_english_historical_spelling
tokenizer_robustness_completion_chinese_partially_romanized
tokenizer_robustness_completion_italian_similar_words
tokenizer_robustness_completion_chinese_keyboard_proximity_errors
tokenizer_robustness_completion_stem_canonical
tokenizer_robustness_completion_english_keyboard_proximity_errors
tokenizer_robustness_completion_stem_colloquial
tokenizer_robustness_completion_english_spelled_out
tokenizer_robustness_completion_turkish_word_reordering
tokenizer_robustness_completion_turkish_english_keyboard
tokenizer_robustness_completion_chinese_space_removal
tokenizer_robustness_completion_italian_dialects
tokenizer_robustness_completion_stem_character_deletion
tokenizer_robustness_completion_turkish_dialects
tokenizer_robustness_completion_farsi_dialects
tokenizer_robustness_completion_chinese_code_language_script_switching
tokenizer_robustness_completion_turkish_similar_words
tokenizer_robustness_completion_english_similar_words
tokenizer_robustness_completion_english_web_search_query
tokenizer_robustness_completion_turkish_colloquial
tokenizer_robustness_completion_english_date_formats
tokenizer_robustness_completion_chinese_equivalent_expressions
tokenizer_robustness_completion_turkish_canonical
tokenizer_robustness_completion_chinese_colloquial
tokenizer_robustness_completion_turkish_web_search_query
tokenizer_robustness_completion_stem_superscript_subscript
tokenizer_robustness_completion_stem_space_removal
tokenizer_robustness_completion_chinese_ocr_errors
tokenizer_robustness_completion_stem_morpheme_separation
tokenizer_robustness_completion_english_letter_repetition_for_emphasis
tokenizer_robustness_completion_english_abbreviations
tokenizer_robustness_completion_italian_spelled_out
tokenizer_robustness_completion_stem_compounds
tokenizer_robustness_completion_turkish_inflections
tokenizer_robustness_completion_math_latex
tokenizer_robustness_completion_chinese_optional_diacritics
tokenizer_robustness_completion_farsi_spelled_out
tokenizer_robustness_completion_stem_double_struck
tokenizer_robustness_completion_italian_abbreviations
tokenizer_robustness_completion_italian_phonetic_spelling
tokenizer_robustness_completion_turkish_derivations
tokenizer_robustness_completion_italian_orthographic_errors
tokenizer_robustness_completion_stem_latex
tokenizer_robustness_completion_stem_canonical
tokenizer_robustness_completion_farsi_word_spacing_zero-width_characters_extra_space
tokenizer_robustness_completion_italian_abbreviations
tokenizer_robustness_completion_english_spaced_styling
tokenizer_robustness_completion_turkish_date_formats
tokenizer_robustness_completion_turkish_keyboard_proximity_errors
tokenizer_robustness_completion_stem_canonical
tokenizer_robustness_completion_farsi_number_romanization
tokenizer_robustness_completion_english_homoglyphs
tokenizer_robustness_completion_chinese_romanization
tokenizer_robustness_completion_italian_orthographic_errors
tokenizer_robustness_completion_math_latex
tokenizer_robustness_completion_italian_phonetic_spelling
tokenizer_robustness_completion_stem_superscript_subscript
tokenizer_robustness_completion_italian_spelled_out
tokenizer_robustness_completion_chinese_word_spacing_zero-width_characters_extra_space
tokenizer_robustness_completion_english_contractions
tokenizer_robustness_completion_farsi_keyboard_proximity_errors
tokenizer_robustness_completion_stem_colloquial
tokenizer_robustness_completion_stem_superscript_subscript
tokenizer_robustness_completion_turkish_code_language_script_switching
tokenizer_robustness_completion_english_emoji_substitution
tokenizer_robustness_completion_stem_colloquial
tokenizer_robustness_completion_chinese_canonical
tokenizer_robustness_completion_italian_dialects
tokenizer_robustness_completion_turkish_orthographic_errors
tokenizer_robustness_completion_stem_morpheme_separation
tokenizer_robustness_completion_stem_compounds
tokenizer_robustness_completion_chinese_traditional
tokenizer_robustness_completion_english_character_deletion
tokenizer_robustness_completion_stem_compounds
tokenizer_robustness_completion_stem_morpheme_separation
tokenizer_robustness_completion_english_macron_diacritic
tokenizer_robustness_completion_english_lowercase
tokenizer_robustness_completion_italian_contractions
tokenizer_robustness_completion_italian_capitalization
tokenizer_robustness_completion_english_scripted_text
tokenizer_robustness_completion_english_superscript_subscript_styling
tokenizer_robustness_completion_farsi_optional_diacritics
tokenizer_robustness_completion_italian_similar_words
tokenizer_robustness_completion_chinese_spelled_out
tokenizer_robustness_completion_stem_upside_down_rotated
tokenizer_robustness_completion_chinese_optional_diacritics
tokenizer_robustness_completion_english_compounds
tokenizer_robustness_completion_italian_similar_words
tokenizer_robustness_completion_stem_upside_down_rotated
tokenizer_robustness_completion_chinese_keyboard_proximity_errors
tokenizer_robustness_completion_italian_contractions
tokenizer_robustness_completion_italian_capitalization
tokenizer_robustness_completion_math_decorative_unicode
tokenizer_robustness_completion_turkish_inflections
tokenizer_robustness_completion_farsi_canonical
tokenizer_robustness_completion_stem_enclosed_characters
tokenizer_robustness_completion_chinese_code_language_script_switching
tokenizer_robustness_completion_stem_unusual_formatting
tokenizer_robustness_completion_italian_dialects
tokenizer_robustness_completion_english_colloquial
tokenizer_robustness_completion_farsi_arabic_keyboard_for_farsi
tokenizer_robustness_completion_stem_enclosed_characters
tokenizer_robustness_completion_turkish_derivations
tokenizer_robustness_completion_stem_unusual_formatting
tokenizer_robustness_completion_english_space_removal
tokenizer_robustness_completion_english_grammatical_errors
tokenizer_robustness_completion_math_farsi
tokenizer_robustness_completion_stem_spelled_out
tokenizer_robustness_completion_english_canonical
tokenizer_robustness_completion_chinese_ocr_errors
tokenizer_robustness_completion_turkish_typographical_errors
tokenizer_robustness_completion_stem_unicode_formatting
tokenizer_robustness_completion_stem_spelled_out
tokenizer_robustness_completion_math_canonical
tokenizer_robustness_completion_chinese_partially_romanized
tokenizer_robustness_completion_italian_spelled_out
tokenizer_robustness_completion_stem_unicode_formatting
tokenizer_robustness_completion_farsi_romanization
tokenizer_robustness_completion_turkish_dialects
tokenizer_robustness_completion_chinese_colloquial
tokenizer_robustness_completion_stem_diacriticized_styling
tokenizer_robustness_completion_italian_phonetic_spelling
tokenizer_robustness_completion_chinese_equivalent_expressions
tokenizer_robustness_completion_english_word_reordering
tokenizer_robustness_completion_italian_orthographic_errors
tokenizer_robustness_completion_english_capitalization
tokenizer_robustness_completion_turkish_word_reordering
tokenizer_robustness_completion_turkish_english_keyboard
tokenizer_robustness_completion_italian_abbreviations
tokenizer_robustness_completion_english_inflections
tokenizer_robustness_completion_turkish_web_search_query
tokenizer_robustness_completion_stem_diacriticized_styling
tokenizer_robustness_completion_math_turkish
tokenizer_robustness_completion_turkish_colloquial
tokenizer_robustness_completion_turkish_similar_words
tokenizer_robustness_completion_chinese_space_removal
tokenizer_robustness_completion_turkish_canonical
tokenizer_robustness_completion_stem_strikethrough
tokenizer_robustness_completion_stem_equivalent_expressions
tokenizer_robustness_completion_chinese_keyboard_proximity_errors
tokenizer_robustness_completion_stem_fullwidth_characters
tokenizer_robustness_completion_italian_numerical_formats
tokenizer_robustness_completion_english_ocr_errors
tokenizer_robustness_completion_stem_strikethrough
tokenizer_robustness_completion_stem_equivalent_expressions
tokenizer_robustness_completion_chinese_optional_diacritics
tokenizer_robustness_completion_stem_fullwidth_characters
tokenizer_robustness_completion_italian_typographical_errors
tokenizer_robustness_completion_english_orthographic_errors
tokenizer_robustness_completion_italian_grammatical_errors
tokenizer_robustness_completion_italian_date_formats
tokenizer_robustness_completion_math_chinese
tokenizer_robustness_completion_stem_scripted_text
tokenizer_robustness_completion_turkish_equivalent_expressions
tokenizer_robustness_completion_chinese_code_language_script_switching
tokenizer_robustness_completion_farsi_dialects
tokenizer_robustness_completion_italian_code_language_script_switching
tokenizer_robustness_completion_stem_scripted_text
tokenizer_robustness_completion_farsi_spelled_out
tokenizer_robustness_completion_stem_typographical_errors
tokenizer_robustness_completion_chinese_partially_romanized
tokenizer_robustness_completion_italian_canonical
tokenizer_robustness_completion_english_character_substitution
tokenizer_robustness_completion_italian_plausible_diacritics_errors
tokenizer_robustness_completion_math_spelled_out
tokenizer_robustness_completion_stem_typographical_errors
tokenizer_robustness_completion_english_hyphenated_spelling
tokenizer_robustness_completion_chinese_ocr_errors
tokenizer_robustness_completion_italian_web_search_query
tokenizer_robustness_completion_chinese_space_removal
tokenizer_robustness_completion_chinese_colloquial
tokenizer_robustness_completion_italian_keyboard_proximity_errors
tokenizer_robustness_completion_italian_english_keyboard
tokenizer_robustness_completion_chinese_equivalent_expressions
tokenizer_robustness_completion_english_spelled_out
tokenizer_robustness_completion_chinese_romanization
tokenizer_robustness_completion_italian_english_keyboard
tokenizer_robustness_completion_math_italian
tokenizer_robustness_completion_italian_keyboard_proximity_errors
tokenizer_robustness_completion_english_date_formats
tokenizer_robustness_completion_italian_web_search_query
tokenizer_robustness_completion_english_similar_words
tokenizer_robustness_completion_english_web_search_query
tokenizer_robustness_completion_english_historical_spelling
tokenizer_robustness_completion_stem_double_struck
tokenizer_robustness_completion_stem_latex
tokenizer_robustness_completion_stem_double_struck
tokenizer_robustness_completion_chinese_word_spacing_zero-width_characters_extra_space
tokenizer_robustness_completion_italian_plausible_diacritics_errors
tokenizer_robustness_completion_english_keyboard_proximity_errors
tokenizer_robustness_completion_stem_latex
tokenizer_robustness_completion_italian_canonical
tokenizer_robustness_completion_math_space_removal
tokenizer_robustness_completion_italian_code_language_script_switching
tokenizer_robustness_completion_italian_date_formats
tokenizer_robustness_completion_chinese_canonical
tokenizer_robustness_completion_chinese_traditional
tokenizer_robustness_completion_english_letter_repetition_for_emphasis
tokenizer_robustness_completion_farsi_colloquial
tokenizer_robustness_completion_italian_grammatical_errors
tokenizer_robustness_completion_turkish_spelled_out
tokenizer_robustness_completion_stem_character_deletion
tokenizer_robustness_completion_chinese_spelled_out
tokenizer_robustness_completion_english_abbreviations
tokenizer_robustness_completion_stem_space_removal
tokenizer_robustness_completion_italian_typographical_errors
tokenizer_robustness_completion_farsi_equivalent_expressions
tokenizer_robustness_completion_stem_character_deletion
tokenizer_robustness_completion_farsi_code_language_script_switching
tokenizer_robustness_completion_turkish_grammatical_errors
tokenizer_robustness_completion_italian_numerical_formats

We want a summary table like below

| filtering_mode   | model_name   | task                                                      | task_pretty_name     |   canonical_count |   num_samples | category                 | langs    |   acc_norm |   acc_norm_std |      acc |   acc_std | canonical_task_name                            |   canonical_acc |   canonical_acc_norm |
|:-----------------|:-------------|:----------------------------------------------------------|:---------------------|------------------:|--------------:|:-------------------------|:---------|-----------:|---------------:|---------:|----------:|:-----------------------------------------------|----------------:|---------------------:|
| no_filter        | Aya          | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.294118 |       0.469668 | 0.352941 |  0.492592 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 |
| no_filter        | BLOOM        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 |
| no_filter        | ByT5         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 |
| no_filter        | Comma        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 |
| no_filter        | GPT-2        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.235294 |  0.437237 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.823529 |
| no_filter        | GPT-4o       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.352941 |  0.492592 | tokenizer_robustness_completion_stem_canonical |        1        |             0.941176 |
| no_filter        | Gemma-2      | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.882353 |
| no_filter        | Llama-3.2    | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.882353 |
| no_filter        | Phi-3        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.235294 |  0.437237 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 |
| no_filter        | Qwen-3       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.294118 |       0.469668 | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 |
| no_filter        | Tekken       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.235294 |       0.437237 | 0.176471 |  0.392953 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.882353 |
| no_filter        | TokenMonster | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.294118 |       0.469668 | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.764706 |
| no_filter        | XGLM         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.823529 |       0.392953 | 0.882353 |  0.332106 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 |
| no_filter        | mBERT        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.235294 |       0.437237 | 0.294118 |  0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.764706 |


started with this

|          |                     |            |     |          |                   |                     |             |                  |                     |                     |
| -------- | ------------------- | ---------- | --- | -------- | ----------------- | ------------------- | ----------- | ---------------- | ------------------- | ------------------- |
| Category | Perturbation (Task) | Model name | acc | acc_norm | number of samples | filter              | acc_std_err | acc_norm_std_err | number of canonical | number of perturbed |
|          | romanization        | Comma      |     |          |                   | only_canonical_true |             |                  |                     |                     |
|          | dialect             | Comma      |     |          |                   | only_canonical_true |             |                  |                     |                     |
|          | romanization        | Comma      |     |          |                   | no_filter           |             |                  |                     |                     |
|          | dialect             | Comma      |     |          |                   | no_filter           |             |                  |                     |                     |
|          |                     |            |     |          |                   | only_canonical      |             |                  |                     |                     |
|          |                     |            |     |          |                   | only_perturbed      |             |                  |                     |                     |

In [412]:
import warnings

from category_mapping import SUBCATEGORY_TO_CATEGORY
from typing import List

FILTERS = [
    "no_filter",
    "only_canonical_correct",
    "canonical_wrong_at_least_one_perturb_correct",
    "remains_or_becomes_correct",
]
keys = {
    "no_filter": (False, False, False),
    "only_canonical_correct": (True, False, False),
    "canonical_wrong_at_least_one_perturb_correct": (False, False, True),
    "remains_or_becomes_correct": (False, True, False),
}


def get_group_name(task_name):
    if "stem" in task_name:
        return "tokenizer_robustness_completion_stem"
    elif "english" in task_name:
        return "tokenizer_robustness_completion_english"
    elif "turkish" in task_name:
        return "tokenizer_robustness_completion_turkish"
    elif "farsi" in task_name:
        return "tokenizer_robustness_completion_farsi"
    elif "italian" in task_name:
        return "tokenizer_robustness_completion_italian"
    elif "chinese" in task_name:
        return "tokenizer_robustness_completion_chinese"
    elif "math" in task_name:
        return "tokenizer_robustness_completion_math"
    elif "general" in task_name:
        return "tokenizer_robustness_completion_general"


all_tasks = all_samples["task_pretty_name"].unique()
all_tasks = all_samples["task"].unique()
model_names = all_samples["model_name"].unique()
## cleanup secondary categories
all_samples["final_category"] = all_samples["category"].apply(
    lambda x: str(x).split(",")[0]
)
### TODO: replace later
# ## stem doesn't have lang for some reason, hacking it for now
# all_samples["lang"]=all_samples.apply(lambda row: "eng_Latn" if row["lang"] )


def get_summaries(subcategories: List[str] = None):
    all_summaries = []
    for filtering_mode in FILTERS:
        #################### filtering & clean-up ####################
        # don't rely on canonical_df, perturbed_df, always use samples
        samples, canonical_df, perturbed_df = get_canonical_and_perturbed_df(
            all_samples, *keys[filtering_mode], verbose=False
        )
        ## remove duplicate results just in case they were run twice
        dup_keys = [
            "model_name",
            "task",
            "subcategories",
            "lang",
            "set_id",
            "var_id",
            "question",
        ]
        duplicate_count = (
            samples.groupby(dup_keys, as_index=False).size()["size"] > 1
        ).sum()
        print(f"N duplicates: {duplicate_count}")
        samples = samples.drop_duplicates(subset=dup_keys)
        metadata = {"filtering_mode": filtering_mode}
        #################### process results for each model ####################
        for model in model_names:
            df_filter_ = samples["model_name"] == model
            metadata["model_name"] = model
            model_df = samples[df_filter_]
            #################### process results for each model & task pair ####################
            for task in all_tasks:
                tmp = model_df[model_df["task"] == task]
                if len(tmp) == 0 and filtering_mode == "no_filter":
                    warnings.warn(
                        f"Oh noo, check for model: {model}, task: {task} if it is run, the df is empty, skipping for now..."
                    )
                if len(tmp) == 0:
                    continue
                task_pretty_name = tmp["task_pretty_name"].unique()[0]
                if subcategories and task_pretty_name not in subcategories:
                    continue
                #################### extract canonical information ####################
                task_group_name = get_group_name(task)
                cor_canonical_task_name = f"{task_group_name}_canonical"
                ## apply filtering: canonical examples, match set ids and match tasks group name
                corr_canonical = model_df[
                    model_df["is_canonical"]
                    & model_df["set_id"].isin(tmp["set_id"].unique())
                    # & model_df[model_df["task"].str.startswith(task_group_name)]
                ]
                canonical_count = len(corr_canonical)

                if len(tmp) == 0:
                    pass
                    print(f"Empty df for task {task} under filter: {filtering_mode}")
                    continue
                category = tmp["final_category"].unique()
                category = SUBCATEGORY_TO_CATEGORY.get(task_pretty_name, "")
                metadata.update(
                    {
                        "task": task,
                        "task_pretty_name": task_pretty_name,
                        "canonical_count": canonical_count,
                        "num_samples": len(tmp),
                        "category": category,
                        "langs": ",".join([l for l in tmp["lang"].unique() if l != ""]),
                    }
                )
                # compute accuracy metrics
                acc_norm = tmp["acc_norm"].mean()
                acc_norm_std = tmp["acc_norm"].std()
                acc = tmp["acc"].mean()
                acc_std = tmp["acc"].std()
                summary = {
                    "acc_norm": tmp["acc_norm"].mean(),
                    "acc_norm_std": tmp["acc_norm"].std(),
                    "acc": tmp["acc"].mean(),
                    "acc_std": tmp["acc"].std(),
                    "canonical_task_name": cor_canonical_task_name,
                    "canonical_acc": corr_canonical["acc"].mean(),
                    "canonical_acc_norm": corr_canonical["acc_norm"].mean(),
                    "group_name": task_group_name,
                }
                all_summaries.append(metadata | summary)

    all_summaries = pd.DataFrame.from_records(all_summaries)
    return all_summaries


all_summaries = get_summaries()

N duplicates: 30604
N duplicates: 61193
N duplicates: 21964
N duplicates: 63314

In [413]:
# langs = all_summaries["langs"].unique()
# langs
corr_canonical

,doc_id,target,metrics,acc,acc_norm,model_name,tokenizer_name,task,question,choices,...,token_counts.tokenmonster/englishcode-32000-consistent-v1,question_general_category,categories,task_pretty_name,vocab_bucket,is_canonical,var_id,final_category,canonical_acc_norm,canonical-perturbed_acc_norm
4428,8,0,"[acc, acc_norm]",0,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,"int(0, 1) represents","[definite integral from 0 to 1, indefinite int...",...,6.0,Mathematics,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4430,9,1,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,A polygon with three sides is called a,"[square, triangle, circle, rectangle]",...,6.0,Mathematics/Geometry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4448,18,3,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula H2SO4 represents,"[hydrogen sulfate, sulfur tetroxide, bisulfate...",...,8.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4450,19,0,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula CH4 represents,"[methane, water, benzene, oxygen]",...,7.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4452,20,0,"[acc, acc_norm]",0,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula CO2 represents,"[carbon dioxide, carbon monoxide, oxygen, carbon]",...,6.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4454,21,1,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula O2 represents,"[water, oxygen, ozone, air]",...,6.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4456,22,0,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula H2 represents,"[hydrogen, water, helium, gas]",...,6.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4458,23,2,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula N2 represents,"[ammonia, nitrate, nitrogen, air]",...,6.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4460,24,1,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula NH3 represents,"[nitrogen, ammonia, hydrogen, gas]",...,7.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4464,26,0,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula CaCO3 represents,"[calcium carbonate, calcium oxide, carbon diox...",...,8.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4468,28,0,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,The chemical formula for water is,"[H2O, H2SO4, NaCl, CO2]",...,6.0,Chemistry,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4480,34,2,"[acc, acc_norm]",0,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,m/s2 represents,"[velocity, distance, acceleration, speed]",...,4.0,Physics/Mathematics,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4482,35,1,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,m3 is the unit of,"[area, volume, density, mass]",...,5.0,Physics/Mathematics,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4484,36,1,"[acc, acc_norm]",0,0,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,m2 is the unit of,"[volume, area, perimeter, density]",...,5.0,Physics/Mathematics,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN
4486,38,1,"[acc, acc_norm]",1,1,mBERT,google-bert/bert-base-multilingual-cased,tokenizer_robustness_completion_stem_canonical,kg*m2/s2 represents,"[momentum, energy, force, mass]",...,7.0,Physics/Mathematics,NaN,Canonical,Medium,True,0.0,nan,NaN,NaN

In [414]:
## sanity check
print(
    all_summaries[
        all_summaries["task_pretty_name"] == "Fullwidth Characters"
    ].to_markdown(index=False)
)

| filtering_mode                               | model_name   | task                                                      | task_pretty_name     |   canonical_count |   num_samples | category                 | langs    |   acc_norm |   acc_norm_std |      acc |    acc_std | canonical_task_name                            |   canonical_acc |   canonical_acc_norm | group_name                           |
|:---------------------------------------------|:-------------|:----------------------------------------------------------|:---------------------|------------------:|--------------:|:-------------------------|:---------|-----------:|---------------:|---------:|-----------:|:-----------------------------------------------|----------------:|---------------------:|:-------------------------------------|
| no_filter                                    | Aya          | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.294118 |       0.469668 | 0.352941 |   0.492592 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | BLOOM        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | ByT5         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | Comma        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | GPT-2        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.235294 |   0.437237 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | GPT-4o       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.352941 |   0.492592 | tokenizer_robustness_completion_stem_canonical |        1        |             0.941176 | tokenizer_robustness_completion_stem |
| no_filter                                    | Gemma-2      | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.882353 | tokenizer_robustness_completion_stem |
| no_filter                                    | Llama-3.2    | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.352941 |       0.492592 | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.882353 | tokenizer_robustness_completion_stem |
| no_filter                                    | Phi-3        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.235294 |   0.437237 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | Qwen-3       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.294118 |       0.469668 | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | Tekken       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.235294 |       0.437237 | 0.176471 |   0.392953 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.882353 | tokenizer_robustness_completion_stem |
| no_filter                                    | TokenMonster | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.294118 |       0.469668 | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.764706 | tokenizer_robustness_completion_stem |
| no_filter                                    | XGLM         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.823529 |       0.392953 | 0.882353 |   0.332106 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.823529 | tokenizer_robustness_completion_stem |
| no_filter                                    | mBERT        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.235294 |       0.437237 | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.882353 |             0.764706 | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | Aya          | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   0.357143 |       0.497245 | 0.428571 |   0.513553 | tokenizer_robustness_completion_stem_canonical |        0.928571 |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | BLOOM        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   0.5      |       0.518875 | 0.214286 |   0.425815 | tokenizer_robustness_completion_stem_canonical |        0.928571 |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | ByT5         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   0.5      |       0.518875 | 0.285714 |   0.468807 | tokenizer_robustness_completion_stem_canonical |        0.928571 |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | Comma        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   0.428571 |       0.513553 | 0.357143 |   0.497245 | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | GPT-2        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   0.428571 |       0.513553 | 0.285714 |   0.468807 | tokenizer_robustness_completion_stem_canonical |        0.928571 |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | GPT-4o       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                16 |            16 | Structural Text Elements | eng_Latn |   0.375    |       0.5      | 0.375    |   0.5      | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | Gemma-2      | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                15 |            15 | Structural Text Elements | eng_Latn |   0.466667 |       0.516398 | 0.333333 |   0.48795  | tokenizer_robustness_completion_stem_canonical |        0.933333 |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | Llama-3.2    | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                15 |            15 | Structural Text Elements | eng_Latn |   0.4      |       0.507093 | 0.266667 |   0.457738 | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | Phi-3        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   0.5      |       0.518875 | 0.285714 |   0.468807 | tokenizer_robustness_completion_stem_canonical |        0.928571 |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | Qwen-3       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   0.357143 |       0.497245 | 0.285714 |   0.468807 | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | Tekken       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                15 |            15 | Structural Text Elements | eng_Latn |   0.266667 |       0.457738 | 0.2      |   0.414039 | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | TokenMonster | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                13 |            13 | Structural Text Elements | eng_Latn |   0.384615 |       0.50637  | 0.153846 |   0.375534 | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | XGLM         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                14 |            14 | Structural Text Elements | eng_Latn |   1        |       0        | 1        |   0        | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| only_canonical_correct                       | mBERT        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                13 |            13 | Structural Text Elements | eng_Latn |   0.307692 |       0.480384 | 0.384615 |   0.50637  | tokenizer_robustness_completion_stem_canonical |        0.923077 |             1        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | Aya          | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 1 |             1 | Structural Text Elements | eng_Latn |   0        |     nan        | 0        | nan        | tokenizer_robustness_completion_stem_canonical |        1        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | BLOOM        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 1 |             1 | Structural Text Elements | eng_Latn |   0        |     nan        | 1        | nan        | tokenizer_robustness_completion_stem_canonical |        1        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | ByT5         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 1 |             1 | Structural Text Elements | eng_Latn |   0        |     nan        | 1        | nan        | tokenizer_robustness_completion_stem_canonical |        1        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | Comma        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 1 |             1 | Structural Text Elements | eng_Latn |   0        |     nan        | 0        | nan        | tokenizer_robustness_completion_stem_canonical |        0        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | GPT-2        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 2 |             2 | Structural Text Elements | eng_Latn |   0        |       0        | 0        |   0        | tokenizer_robustness_completion_stem_canonical |        1        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | Gemma-2      | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 2 |             2 | Structural Text Elements | eng_Latn |   0        |       0        | 0        |   0        | tokenizer_robustness_completion_stem_canonical |        1        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | Phi-3        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 2 |             2 | Structural Text Elements | eng_Latn |   0        |       0        | 0        |   0        | tokenizer_robustness_completion_stem_canonical |        1        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | Qwen-3       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 2 |             2 | Structural Text Elements | eng_Latn |   0        |       0        | 0.5      |   0.707107 | tokenizer_robustness_completion_stem_canonical |        0.5      |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | Tekken       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 1 |             1 | Structural Text Elements | eng_Latn |   0        |     nan        | 0        | nan        | tokenizer_robustness_completion_stem_canonical |        1        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | TokenMonster | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 3 |             3 | Structural Text Elements | eng_Latn |   0        |       0        | 1        |   0        | tokenizer_robustness_completion_stem_canonical |        0.666667 |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | XGLM         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 1 |             1 | Structural Text Elements | eng_Latn |   0        |     nan        | 0        | nan        | tokenizer_robustness_completion_stem_canonical |        0        |             0        | tokenizer_robustness_completion_stem |
| canonical_wrong_at_least_one_perturb_correct | mBERT        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                 3 |             3 | Structural Text Elements | eng_Latn |   0        |       0        | 0        |   0        | tokenizer_robustness_completion_stem_canonical |        0.666667 |             0        | tokenizer_robustness_completion_stem |
| remains_or_becomes_correct                   | Aya          | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                15 |            15 | Structural Text Elements | eng_Latn |   0.333333 |       0.48795  | 0.4      |   0.507093 | tokenizer_robustness_completion_stem_canonical |        0.933333 |             0.933333 | tokenizer_robustness_completion_stem |
| remains_or_becomes_correct                   | BLOOM        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                15 |            15 | Structural Text Elements | eng_Latn |   0.466667 |       0.516398 | 0.266667 |   0.457738 | tokenizer_robustness_completion_stem_canonical |        0.933333 |             0.933333 | tokenizer_robustness_completion_stem |
| remains_or_becomes_correct                   | ByT5         | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                15 |            15 | Structural Text Elements | eng_Latn |   0.466667 |       0.516398 | 0.333333 |   0.48795  | tokenizer_robustness_completion_stem_canonical |        0.933333 |             0.933333 | tokenizer_robustness_completion_stem |
| remains_or_becomes_correct                   | Comma        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                15 |            15 | Structural Text Elements | eng_Latn |   0.4      |       0.507093 | 0.333333 |   0.48795  | tokenizer_robustness_completion_stem_canonical |        0.933333 |             0.933333 | tokenizer_robustness_completion_stem |
| remains_or_becomes_correct                   | GPT-2        | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                16 |            16 | Structural Text Elements | eng_Latn |   0.375    |       0.5      | 0.25     |   0.447214 | tokenizer_robustness_completion_stem_canonical |        0.9375   |             0.875    | tokenizer_robustness_completion_stem |
| remains_or_becomes_correct                   | GPT-4o       | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                16 |            16 | Structural Text Elements | eng_Latn |   0.375    |       0.5      | 0.375    |   0.5      | tokenizer_robustness_completion_stem_canonical |        1        |             1        | tokenizer_robustness_completion_stem |
| remains_or_becomes_correct                   | Gemma-2      | tokenizer_robustness_completion_stem_fullwidth_characters | Fullwidth Characters |                17 |            17 | Structural Text Elements | eng_Latn |   0.411765 |       0.5073   | 0.294118 |   0.469668 | tokenizer_robustness_completion_stem_canonical |        0.941176 |             0.882353 | tokenizer_robustness_completion_stem |

In [415]:
save_path = OUTPUT_DIR / "summary.tsv"

all_summaries.to_csv(save_path, sep="\t")
print(f"File saved at \n{save_path}")

File saved at
output/results-v5/summary/all/summary.tsv

# Pivot Views

In [416]:
import pandas as pd
import numpy as np


# Modified function to exclude aggregation rows
def highlight_extremes(s):
    """
    Highlight the max value in green and min value in red for each column
    Excludes aggregation rows from min/max calculation
    """
    if s.dtype != "object":  # Only apply to numeric columns
        # Define patterns that identify aggregation rows
        aggregation_patterns = [
            "MEAN",
            "STD",
            "MIN",
            "MAX",
            "MEDIAN",
            "RANGE",
            "TOP_3_AVG",
            "BOTTOM_3_AVG",
            "TASK_WEIGHTED_AVG",
            "BEST_MODEL_PER_TASK",
            "WORST_MODEL_PER_TASK",
            "─",
            "═",
            "___",  # Visual separators
        ]

        # Filter out aggregation rows for min/max calculation
        model_only_series = s.copy()
        model_indices_to_exclude = []

        for idx in s.index:
            # Check if index matches any aggregation pattern
            if any(pattern in str(idx).upper() for pattern in aggregation_patterns):
                model_indices_to_exclude.append(idx)

        # Remove aggregation rows from calculation
        model_only_series = model_only_series.drop(
            model_indices_to_exclude, errors="ignore"
        )

        # Calculate min/max only from model rows
        if len(model_only_series) > 0:
            max_val = model_only_series.max()
            min_val = model_only_series.min()
        else:
            max_val = None
            min_val = None

        styles = []
        for idx, val in s.items():
            # Don't highlight aggregation rows at all
            if any(pattern in str(idx).upper() for pattern in aggregation_patterns):
                styles.append("")
            elif pd.isna(val):
                styles.append("")
            elif max_val is not None and val == max_val:
                styles.append(
                    "background-color: #90EE90; font-weight: bold; color: #006400"
                )  # Light green bg, dark green text
            elif min_val is not None and val == min_val:
                styles.append(
                    "background-color: #FFB6C1; font-weight: bold; color: #8B0000"
                )  # Light red bg, dark red text
            else:
                styles.append("")
        return styles
    else:
        return [""] * len(s)


def weighted_avg(group):
    """
    Calculate weighted average from a group that has both acc_norm and num_samples
    """
    if len(group) == 0:
        return "___"

    # group is a DataFrame with both columns
    acc_values = group["acc_norm"]
    weights = group["num_samples"]

    # Remove NaN values
    valid_mask = ~(pd.isna(acc_values) | pd.isna(weights)) & (weights > 0)

    if valid_mask.sum() > 0:
        return np.average(acc_values[valid_mask], weights=weights[valid_mask])
    else:
        return "___"


def get_styled_df(summaries, columns=["task_pretty_name", "langs"]):
    pivot_df = (
        summaries.groupby(["model_name", *columns])
        .apply(weighted_avg)
        .reset_index()  # Convert back to DataFrame
        .rename(columns={0: "weighted_avg"})  # Name the result column
        .pivot_table(index="model_name", columns=columns, values="weighted_avg")
    )

    # Add aggregate columns
    pivot_df["Mean"] = pivot_df.mean(axis=1)
    # Sort by mean performance
    pivot_df = pivot_df.sort_values("Mean", ascending=False)

    # add column-wise stats
    pivot_df.loc["─" * 20] = np.nan  # Separator row
    pivot_df.loc["MEAN"] = pivot_df.mean(axis=0)
    pivot_df.loc["STD"] = pivot_df.std(axis=0)

    styled_df = (
        pivot_df.style.apply(highlight_extremes, axis=0)
        .format(precision=3)
        .set_table_styles(
            [
                {
                    "selector": "th.level0",
                    "props": [
                        ("border-right", "3px solid black"),
                        ("text-align", "center"),
                    ],
                },
                {
                    "selector": "td",
                    "props": [("text-align", "center"), ("font-size", "11px")],
                },
            ]
        )
    )
    styled_df = styled_df.format(na_rep="─────")
    return styled_df

## Structural Text Elements

In [417]:
styling_categories = [
    "Scripted text",
    "Macron Diacritic",
    "Fullwidth Characters",
    "Upside Down/Rotated",
    "Double struck",
    "Enclosed Characters",
    "Strikethrough",
    "Diacriticized styling",
]
style_summaries = all_summaries[
    (all_summaries["filtering_mode"] == FILTER)
    & all_summaries["task_pretty_name"].isin(styling_categories)
]
style_summaries

,filtering_mode,model_name,task,task_pretty_name,canonical_count,num_samples,category,langs,acc_norm,acc_norm_std,acc,acc_std,canonical_task_name,canonical_acc,canonical_acc_norm,group_name
1721,only_canonical_correct,Aya,tokenizer_robustness_completion_english_macron...,Macron Diacritic,133,40,Structural Text Elements,eng_Latn,0.250000,0.438529,0.225000,0.422902,tokenizer_robustness_completion_english_canonical,0.924812,1.0,tokenizer_robustness_completion_english
1723,only_canonical_correct,Aya,tokenizer_robustness_completion_english_script...,Scripted text,133,40,Structural Text Elements,eng_Latn,0.325000,0.474342,0.200000,0.405096,tokenizer_robustness_completion_english_canonical,0.924812,1.0,tokenizer_robustness_completion_english
1758,only_canonical_correct,Aya,tokenizer_robustness_completion_stem_diacritic...,Diacriticized styling,11,47,Structural Text Elements,eng_Latn,0.425532,0.499769,0.404255,0.496053,tokenizer_robustness_completion_stem_canonical,1.000000,1.0,tokenizer_robustness_completion_stem
1760,only_canonical_correct,Aya,tokenizer_robustness_completion_stem_double_st...,Double struck,15,15,Structural Text Elements,eng_Latn,0.400000,0.507093,0.200000,0.414039,tokenizer_robustness_completion_stem_canonical,0.933333,1.0,tokenizer_robustness_completion_stem
1761,only_canonical_correct,Aya,tokenizer_robustness_completion_stem_enclosed_...,Enclosed Characters,11,36,Structural Text Elements,eng_Latn,0.305556,0.467177,0.166667,0.377964,tokenizer_robustness_completion_stem_canonical,1.000000,1.0,tokenizer_robustness_completion_stem
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,only_canonical_correct,mBERT,tokenizer_robustness_completion_stem_enclosed_...,Enclosed Characters,11,36,Structural Text Elements,eng_Latn,0.194444,0.401386,0.083333,0.280306,tokenizer_robustness_completion_stem_canonical,1.000000,1.0,tokenizer_robustness_completion_stem
3296,only_canonical_correct,mBERT,tokenizer_robustness_completion_stem_fullwidth...,Fullwidth Characters,13,13,Structural Text Elements,eng_Latn,0.307692,0.480384,0.384615,0.506370,tokenizer_robustness_completion_stem_canonical,0.923077,1.0,tokenizer_robustness_completion_stem
3297,only_canonical_correct,mBERT,tokenizer_robustness_completion_stem_scripted_...,Scripted text,14,14,Structural Text Elements,eng_Latn,0.285714,0.468807,0.142857,0.363137,tokenizer_robustness_completion_stem_canonical,0.928571,1.0,tokenizer_robustness_completion_stem
3298,only_canonical_correct,mBERT,tokenizer_robustness_completion_stem_strikethr...,Strikethrough,11,44,Structural Text Elements,eng_Latn,0.295455,0.461522,0.181818,0.390154,tokenizer_robustness_completion_stem_canonical,1.000000,1.0,tokenizer_robustness_completion_stem
3299,only_canonical_correct,mBERT,tokenizer_robustness_completion_stem_upside_do...,Upside Down/Rotated,12,13,Structural Text Elements,eng_Latn,0.230769,0.438529,0.230769,0.438529,tokenizer_robustness_completion_stem_canonical,0.916667,1.0,tokenizer_robustness_completion_stem

In [418]:
save_path = OUTPUT_DIR / "style_summary.tsv"

style_summaries.to_csv(save_path, sep="\t")
print(f"File saved at \n{save_path}")

File saved at
output/results-v5/summary/all/style_summary.tsv

In [419]:
styled_df = get_styled_df(style_summaries, columns=["task_pretty_name", "langs"])

# Set caption
styled_df = styled_df.set_caption(
    f"Unicode Characters (Green=Best, Red=Worst) {FILTER}"
)
styled_df

/var/folders/8n/l2sy_xnn4fv5j3b8z0dhfxlh0000gn/T/ipykernel_35969/2339757082.py:97: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(weighted_avg)

## Noise

In [420]:
multilingual_noise = [
    "Keyboard proximity errors",
    "Space removal",
    "Character deletion",
    "Typographical errors",
    "OCR Errors",
]

FILTER = "only_canonical_correct"
multilingual_noise_summaries = all_summaries[
    (all_summaries["filtering_mode"] == FILTER)
    & (all_summaries["task_pretty_name"].isin(multilingual_noise))
    # & (~all_summaries["task"].str.contains("stem"))
]

styled_df = get_styled_df(multilingual_noise_summaries)
styled_df

/var/folders/8n/l2sy_xnn4fv5j3b8z0dhfxlh0000gn/T/ipykernel_35969/2339757082.py:97: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(weighted_avg)

## Math

In [ ]:
math_perturbs = [
    "Spelled out",
    "Superscript/subscript",
    "LaTeX",
    "Decorative Unicode",
    "Farsi",
    "Turkish",
    "Italian",
    "Chinese",
]

FILTER = "only_canonical_correct"
math_summaries = all_summaries[
    (all_summaries["filtering_mode"] == FILTER)
    & (all_summaries["task_pretty_name"].isin(math_perturbs))
    & (all_summaries["task"].str.contains("math"))
]

styled_df = get_styled_df(math_summaries, ["task_pretty_name"])
styled_df = styled_df.set_caption(f"MATH {FILTER}")
styled_df

/var/folders/8n/l2sy_xnn4fv5j3b8z0dhfxlh0000gn/T/ipykernel_35969/2339757082.py:97: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(weighted_avg)

In [433]:
latex_perturbs = [
    # "Spelled out",
    # "Superscript/subscript",
    "LaTeX",
    # "Decorative Unicode",
    # "Farsi",
    # "Turkish",
    # "Italian",
    # "Chinese",
]

FILTER = "only_canonical_correct"
math_summaries = all_summaries[
    (all_summaries["filtering_mode"] == FILTER)
    & (all_summaries["task_pretty_name"].isin(latex_perturbs))
    # & (all_summaries["task"].str.contains("math"))
]

styled_df = get_styled_df(math_summaries, ["task_pretty_name", "group_name"])
styled_df = styled_df.set_caption(f"LaTeX {FILTER}")
styled_df

/var/folders/8n/l2sy_xnn4fv5j3b8z0dhfxlh0000gn/T/ipykernel_35969/2339757082.py:97: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(weighted_avg)

## Morphological

In [426]:
morph_perturbs = [
    "Contractions",
        "Inflections",
        "Compounds",
        "Derivations",
        "Morpheme separation",
        # "Spelled out",
]

FILTER = "only_canonical_correct"
morph_summaries = all_summaries[
    (all_summaries["filtering_mode"] == FILTER)
    & (all_summaries["task_pretty_name"].isin(morph_perturbs))
    # & (all_summaries["task"].str.contains("math"))
]

styled_df = get_styled_df(morph_summaries, ["task_pretty_name", "langs"])
styled_df = styled_df.set_caption(f"Morphological Challenges, {FILTER}")
styled_df

/var/folders/8n/l2sy_xnn4fv5j3b8z0dhfxlh0000gn/T/ipykernel_35969/2339757082.py:97: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(weighted_avg)